[
build-system
]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[
project
]
name = "guitar-practice-assistant"
version = "0.1.0"
description = "A guitar practice routine manager"
authors = [
    {name = "Steven"}
]
requires-python = ">=3.10"
dependencies = [
    "flask",
    "google-auth",
    "google-auth-oauthlib", 
    "google-auth-httplib2",
    "gspread",
    "anthropic"
]

[
tool.setuptools
]
packages = ["app"]

[
tool.pylance
]
python.analysis.extraPaths = [".", "app"]